using Volo.Abp.DependencyInjection;

namespace TobaccoDMSystemManagement.AppService;

public interface ITobaccoDMSystemManagementAppService : ITransientDependency;

public class TobaccoDMSystemManagementAppService : ITobaccoDMSystemManagementAppService;